"""user_roles

Revision ID: abc251fbb595
Revises: 
Create Date: 2026-04-21 02:21:05.887563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc251fbb595'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['student_id'])
        batch_op.create_unique_constraint(None, ['teacher_id'])
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])
        batch_op.create_foreign_key(None, 'teachers', ['teacher_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('teacher_id')
        batch_op.drop_column('student_id')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
